import Head from 'next/head'
import { Container, Text } from '@chakra-ui/react';

export default function Home() {
  return (
    <Container
      minW='full'
      minH='full'
      paddingY='24'
      paddingX={{ base: '6', lg: '40' }}
    >
      <Head>
        <title>Payment stripe</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Text
        as='h1'
        fontSize='4xl'
        textAlign='center'
        color='cyan.900'
        fontWeight='medium'
        textTransform='uppercase'
      >
        Welcome!
      </Text>
    </Container>
  )
}


