import Head from 'next/head'
import { Container, HStack } from '@chakra-ui/react';
import Link from 'next/link';

export default function Home() {
  return (
    <Container
      minW='full'
      minH='full'
      paddingY='16'
      paddingX={{ base: '6', lg: '40' }}
    >
      <Head>
        <title>Mobile app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <HStack spacing='6'>
        <Link href='/'>Main</Link>
        <Link href='/mobile'>Mobile</Link>
      </HStack>
    </Container>
  )
}


