import Head from 'next/head'
import { Container } from '@chakra-ui/react';

export default function Home() {
  return (
    <Container
      minW='full'
      minH='full'
      paddingY='16'
      paddingX={{ base: '6', lg: '40' }}
    >
      <Head>
        <title>Payment stripe</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
    </Container>
  )
}


